name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
      - uses: actions/checkout@v2

      - name: Test unit project
        run: .\build.bat src\application passaporteGitaction.dproj
